### ISSUE TITLE
Compatibility with Zoom/Pan Options?

### ISSUE THREAD

**Issue by akrigline** [Oromis/touch-vtt#1]
I haven't had a chance to test this yet but wanted to ask if you've had a chance to test this out in conjunction with [Zoom/Pan Options](https://github.com/itamarcu/ZoomPanOptions). I have a feeling these two modules interact with similar parts of Foundry Core and might conflict.

**Comment by Oromis** [comment]
I just tested it.@itamarcu and I didn't use any conflicting APIs / overrides so feel free to install and use both at the same time :)

**Comment by akrigline** [comment]
Amazing! Thanks @Oromis
