### ISSUE TITLE
Moving Tokens Without Snapping To Grid

### ISSUE THREAD

**Issue by Mooghead** [Oromis/touch-vtt#10]
Currently I have to hold the shift key while tokens are being moved by players on the touchscreen if the intention is to move a token so that it does not snap to grid.  Is it possible to activate a shift key on the touchscreen so that tokens can be moved freely instead of snapping to the grid?

**Comment by Oromis** [comment]
Thanks for the suggestion! That feature sounds very useful, I could add a toggle button in the sidebar that could be activated or deactivated to simulate shift gestures.

**Comment by Mooghead** [comment]
Hallo David!I hope all is well with you!  You may have seen this, but I thought I would send you a link to an article put out by the Foundry Hub for on site games.  They mention TouchVTT a few times as a recommended utility.  Using Foundry for In-Person Gaming - Foundry Hub  Good stuff!
I also wanted to ask if you still have plans to implement a Shift Key toggle on screen.  This is probably the biggest pain for touch screen play as at this time players always snap to screen unless I press and hold the shift key.  I'll post on Git, but thought I would mention it. :)
Alles Gutte!Kevin


| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Using Foundry for In-Person Gaming - Foundry Hub

The pandemic is slowly coming to a close, which means that it’ll be safe to play our favorite tabletop RPG in pe...
 |

 |

 |





-Kevin

We are the music makers and the dreamers of dreams.
 

    On Monday, January 18, 2021, 2:49:59 AM MST, David Bauske ***@***.***> wrote:  
 
 


Thanks for the suggestion! That feature sounds very useful, I could add a toggle button in the sidebar that could be activated or deactivated to simulate shift gestures.

**Comment by Oromis** [comment]
Hi! Thanks for checking in!

I wanted to check the compatibility of Touch-VTT with 0.8.x this weekend - maybe I can implement this feature while I'm at it :) 

Can you send me a link to that article? I would be very much interested!

**Comment by Mooghead** [comment]
Hello David,Here's the link....sorry, I thought I included it!
https://www.foundryvtt-hub.com/guide/using-foundry-for-in-person-gaming/
I am sure you follow the Foudry Reddit, maybe Discord too, it's been nice to see that TouchVTT is becoming more and more mainstream.  With people starting to do in person games again and bringing their VTTs with them I can only imagine it will get even more popular.
Adding shift would be a big issue resolved.

-Kevin

We are the music makers and the dreamers of dreams.
 

    On Friday, May 21, 2021, 8:36:05 AM MST, David Bauske ***@***.***> wrote:  
 
 


Hi! Thanks for checking in!

I wanted to check the compatibility of Touch-VTT with 0.8.x this weekend - maybe I can implement this feature while I'm at it :)

Can you send me a link to that article? I would be very much interested!

**Comment by Oromis** [comment]
The feature is implemented and released as version 1.4.0 :)

![image](https://user-images.githubusercontent.com/1381990/119258540-6491d980-bbca-11eb-8a1b-5cc34619a467.png)

**Comment by Mooghead** [comment]
Fantastic!  Thanks so much, will donate again and post so people know. This is a huge add. Vielen dank!


Sent from Yahoo Mail for iPhone


On Sunday, May 23, 2021, 4:26 AM, David Bauske ***@***.***> wrote:




The feature is implemented and released as version 1.4.0 :)
