### ISSUE TITLE
Cursor out of Window

### ISSUE THREAD

**Issue by zer0ish** [Oromis/touch-vtt#11]
First, very nice other then the 2 finger pan jittering allot with a Surface Pro 7, when not in F11 full screen. Works better in F11 full screen. Still could be smoother though.
When the cursor is in the browser game window TouchVTT works great(other then above)
If you aren't playing in F11 full screen and touch the top of the browser, you lose TouchVTT usage for touching things, zoom and pan still work, until you use a mouse or track pad to move it back to the game window area. Touching the areas in the main window doesn't return the mouse cursor to allow me to select things.

**Comment by Oromis** [comment]
Hm, weird. Thanks for reporting this, I guess this is the same issue as https://github.com/Oromis/touch-vtt/issues/17? Closing this, re-open if you think this is a separate issue.
