### ISSUE TITLE
Feature Request: Moving tokens with waypoints

### ISSUE THREAD

**Issue by illcom94** [Oromis/touch-vtt#12]
We chatted on Discord briefly. It would be great that you could have an option to enable the default touch movement of tokens to match that of a mouse with ctrl click. You could start the move with one finger, then tap a second finger during the move to add a waypoint. Then you could release to activate the token movement along the path drawn.

**Comment by Oromis** [comment]
So, you requested this a long time ago but I only now got around to implementing this feature. Feel free to test it in version 1.8.0 and provide feedback :)
