### ISSUE TITLE
Cannot login as GM or Player

### ISSUE THREAD

**Issue by buttonpushertv** [Oromis/touch-vtt#13]
FVTT: 0.7.9 (running via node.js on a RaspberryPi or logging in to Windows stand-alone app)
Modules: Only TouchVTT and Tidy Settings
Tablet: iPad 7th Gen (regular not Pro)

I can select the GM or Player account but the "Join" button never becomes active or available to click.

I am using a bluetooth keyboard that has a track point mouse-type device but even with that, I cannot click the "join" button.

**Comment by Oromis** [comment]
FoundryVTT doesn't allow iOS clients to log in. Nothing this module can do about that unfortunately...

The idea for this module is to use a windows-based laptop with a touch screen
