### ISSUE TITLE
Module Documentation link goes to non-existent README.md file

### ISSUE THREAD

**Issue by buttonpushertv** [Oromis/touch-vtt#14]
In the Manage Modules dialog, there is a link to "Module Documentation." It attempts to go to "http://(myserver_ip)/README.md" which does not exist. Looking in the module folder and here on GitHub, the only README.md file is the main one for the repo.

Should there be another one somewhere? Or should "Module Documentation" point to the main README.md file on Github?

**Comment by Oromis** [comment]
Thanks for pointing that out. It should point to the readme in this repo, I'll fix the link.
