### ISSUE TITLE
Draw tools eraser

### ISSUE THREAD

**Issue by gohma231** [Oromis/touch-vtt#15]
There is an eraser for measurements, can a similar eraser be added that supports drawing tools?

**Comment by Oromis** [comment]
I guess it could. I'll implement that when I get to it.

**Comment by Oromis** [comment]
Sorry it took so long, it's finally implemented in version 1.6.0 :)

**Comment by Oromis** [comment]
![image](https://user-images.githubusercontent.com/1381990/120322349-9ac70b80-c2e4-11eb-9f9a-aa73836c8615.png)
