### ISSUE TITLE
Unable to change direction of Vision

### ISSUE THREAD

**Issue by Tyreal74** [Oromis/touch-vtt#20]
With a token selected you are not able to alter which direction a token with vision is looking. By default all tokens face south and cannot alter direction. Could a direction changer be added along side the drag movement

**Comment by Oromis** [comment]
Hi, thanks for reporting this! How would you like to see this implemented? 

A two-finger rotation gesture would probably be the most intuitive solution but it would be very hard to implement. Any other suggestions?

**Comment by Tyreal74** [comment]
I'm not totally sure, I'd probably like to see it either change on direction moved or have maybe some little arrows that you can tap to change direction

Arrows might work better as you might want to move direction without changing vision direction

**Comment by Oromis** [comment]
I'm currently investigating how I can add sth to the right-click menu. It seems to be a bit more involved...

**Comment by Tyreal74** [comment]
Appreciate the time you are putting into this, that's why I suggested arrows, they could appear on token selection, or if you long press on the token they appear (unless that's what you meant about right click)

**Comment by Oromis** [comment]
Yeah, that's what I mean with "right click". I'd like to extend the token's context menu with these arrows

**Comment by Tyreal74** [comment]
That'd be a really nice way to handle it actually, can't be any assistance
sadly

**Comment by Oromis** [comment]
This is implemented in version 1.5.0 :) 

![image](https://user-images.githubusercontent.com/1381990/120320729-ca751400-c2e2-11eb-9b05-218e9521752f.png)

**Comment by Tyreal74** [comment]
Amazing! Can't wait to test it!
