### ISSUE TITLE
Conflict with drag-ruler

### ISSUE THREAD

**Issue by GreatGraySkwid** [Oromis/touch-vtt#21]
Hey, libwrapper is reporting the following issues, and I'm not savvy enough to grok whether you or the drag-ruler dev would be able to resolve it, so I'm posting on both modules:
"Potential conflict detected between module 'drag-ruler' and module 'touch-vtt'.
Detected non-libWrapper wrapping of 'MeasuredTemplate.prototype._onDragLeftStart' by module 'drag-ruler'. This will potentially lead to conflicts."
"Potential conflict detected between module 'drag-ruler' and module 'touch-vtt'.
Detected non-libWrapper wrapping of 'MeasuredTemplate.prototype._onDragLeftMove' by module 'drag-ruler'. This will potentially lead to conflicts."
"Potential conflict detected between module 'drag-ruler' and module 'touch-vtt'.
Detected non-libWrapper wrapping of 'MeasuredTemplate.prototype._onDragLeftDrop' by module 'drag-ruler'. This will potentially lead to conflicts."
"Potential conflict detected between module 'drag-ruler' and module 'touch-vtt'.
Detected non-libWrapper wrapping of 'MeasuredTemplate.prototype._onDragLeftCancel' by module 'drag-ruler'. This will potentially lead to conflicts."

**Comment by Zamrod** [comment]
This has been fixed by libWrapper in one of their versions

**Comment by Oromis** [comment]
Ok nice, thanks for letting me know.
