### ISSUE TITLE
Hide the Direction arrows as a global setting/option to show only on Mobile-Improvements

### ISSUE THREAD

**Issue by Juanfrank** [Oromis/touch-vtt#25]
Hello.-

I'm running into this issue where I would like to hide the direction arrows for all my players, but as it is a client-based setting I am not able to do so. I could use the socketlib sync function and turn it off for all players, but I believe there could be a third dropdown option dependent on the existence of the Mobile-Improvements module, which only made that UI appear when on mobile mode).

Thoughts?

**Comment by Oromis** [comment]
Hi! Good suggestion, thanks! 

I'll implement it differently: I think I can show the directional arrows only if the touchscreen is used to trigger the token HUD. This mode would be a new option in the dropdown an I'll also make it the default.

**Comment by Oromis** [comment]
Hm, I spoke too soon. It's not easy to detect if the HUD is opened due to a touch action.

Allowing players to enable directional arrows by the presence of another module is possible, but wouldn't that enable or disable the functionality uniformly for all players? Modules cannot be enabled for just one player...

**Comment by Juanfrank** [comment]
Is there a way to detect whether or not the user is on a PC/Tablet/Cellphone? Me personally, I would only like most if not all of the TouchVTT settings to be on mobile or tablet. Maybe?

**Comment by Oromis** [comment]
Hm, what I could do is detect whether the client has been using the touch screen at some point. If so, directional arrows would show. What do you think?

**Comment by Juanfrank** [comment]
Does it differentiate between mouse clicks and touch behavior? If so I believe it would be a reasonable roundabout way of achieving what I believe.

**Comment by scooper4711** [comment]
This should apply to measurement hud and enlarge button settings too.
An alternate solution for this would be to make all the UI settings default to "no change from base" and have people on a touch UI go in and enable those settings.

Touch UI is not supported by foundry, so a client connecting on touch is the exception, not the rule. The default settings should reflect that. I realize that your use case is different (in person gaming, shared touch UI) from my use case (all remote players, occasionally want to log in to test something/check something from my iPad)

**Comment by ngPescado** [comment]
I would concur with Scooper4711 .. we have remote players but only two have touchscreens (and no other options). It would be great if they could ENABLE the great features of Touch VTT and the rest (usually on overly large setups) could remain on the original systems as if the module was disabled. Possibly easier than "autodetect"?
