### ISSUE TITLE
Measurement Hud not appearing

### ISSUE THREAD

**Issue by GuineaThePig** [Oromis/touch-vtt#27]
The measurement hud seems to not be working at all, we tried on multiple browsers and devices, with only this module active, and still, no one can see the hud

**Comment by Oromis** [comment]
You're right, that seems to have broken with Foundry 0.8.8. Could you tell me your Foundry & TouchVTT version?

**Comment by Oromis** [comment]
Argh, silly me. Forgot to pack one file necessary into the release 1.8.0. That's why it worked for me but not for you. Fixed in v1.8.1.
