### ISSUE TITLE
Mouse must hover on canvas for single-touch actions to work

### ISSUE THREAD

**Issue by suchcodewow** [Oromis/touch-vtt#37]
**Issue**: When mouse is moved out of main canvas (to chat log area or another screen) this occurs:

- tap to select token does not respond
- drag token to move does not respond
- hold to right-click stops responding

When mouse is moved to hover over canvas again the above behaviors stop.

Pinch to pan, 3 finger pan work as expected at all times.

**Expected behavior**: Single-touch functions work at all times no matter where mouse is hovering.

**To reproduce**

1. Disable all mods except _TouchVTT_
2. create a new scene and add 1 or more actor tokens.
3. hover mouse in canvas area to confirm all actions work.
4. Move mouse over chat log or into another window.
5. SIngle-touch actions no longer work.

**Other details**

- No errors in the console of touchscreen client on startup or referesh.
- The touchscreen is a 27" capacitive touch monitor connected via USB on Windows 10 using the WIndows built in touch support.
- I've run through touch config in WIndows and done a calibration.
- The touchscreen monitor is configured to extend the desktop and setup for portrait (flipped) mode in display settings.

@ShawnP in FoundryVTT if there are any questions.  It's certainly possible I've boofed something obvious.  Thanks for your great work!

**Comment by suchcodewow** [comment]
Changed touchscreen display to the default landscape mode- no difference.

**Comment by Aioros** [comment]
Closing as stale, let me know if this issue is still present after updating the module
