### ISSUE TITLE
Cannot Create Measurements with Multiple Nodes

### ISSUE THREAD

**Issue by Mooghead** [Oromis/touch-vtt#4]
When using the measurement tool there is currently no way to create a measurement with a node that changes direction of the measurement.  Is it possible to do this?

**Comment by Oromis** [comment]
I thought about this earlier. I think it would be possible by introducing a new Tool that sort of specialized for this task, but that's quite involved to develop. I might get around to doing this before christmas, but can't promise anything. I'd definitely welcome a pull request on that matter though :)

**Comment by Oromis** [comment]
Sorry for leaving this sit around for so long, but it wasn't simple to implement at all. It's done now, feel free to test it in v1.8.0 of TouchVTT :)

And do provide feedback on the usability or if you notice any bugs.
