### ISSUE TITLE
Feature Request: (player) Button or Config setting to Disable Pan/Zoom on own screen

### ISSUE THREAD

**Issue by knkr03** [Oromis/touch-vtt#41]
Request some method of disabling the 2/3 point pan and zoom feature in Touch VTT. A preference would be a button, but including a "None" setting in the configuration settings would work as well.
We use have been attempting to use TouchVTT as a horizontal in person battlemap. it is quite easy to 2 or 3 point touch and cause both zooming and panning when attempting to move a token on accident.

**Comment by Aioros** [comment]
Solved in v1.12.1
