### ISSUE TITLE
Hide rotation arrows in HUD for tokens with Lock Rotation

### ISSUE THREAD

**Issue by eggdropsoap** [Oromis/touch-vtt#44]
On tables with mixed token styles (like top-down monsters and portrait-style PCs) it's useful to select Lock Rotation in the token configuration for the tokens that shouldn't rotate. With direction arrows enabled in TouchVTT, this creates a UX problem: players with locked-rotation tokens see the arrows, but they do nothing.

TouchVTT should hide the arrow buttons on the token's HUD for locked-rotation tokens, even if “Direction arrows in Token HUD” is set On. This will make the appearance of the token HUD arrows context-sensitive, removing UI elements that are non-functional for that token.

**Comment by Aioros** [comment]
Solved in v1.12.1
