### ISSUE TITLE
Incompatibility with 'Dice So Nice'

### ISSUE THREAD

**Issue by DarioRomano** [Oromis/touch-vtt#45]
Sorry if this is a known or unfixable issue. I've noticed that the current version of TouchVTT seems to not work properly with the popular module 'Dice So Nice'.
I've found that the scene is visible on the mobile device upon entering the game for a short time, and then gets replaced by a black screen. The elements at the bottom of the screen remain functional.

**Comment by FeistyViking** [comment]
By chance, do you happen to be using an iOS or iPadOS device?

We are running into a similar problem but does not seem to be affecting Android devices.

**Comment by DarioRomano** [comment]
> By chance, do you happen to be using an iOS or iPadOS device?
> 
> We are running into a similar problem but does not seem to be affecting Android devices.

I had the issue on a OnePlus 8 running Android 12 and the Chrome app.
