### ISSUE TITLE
Right-Clicking via long-press doesn't work for Gamemasters

### ISSUE THREAD

**Issue by wickermoon** [Oromis/touch-vtt#46]
As is mentioned in issue #29 , there is a problem with the long-press context-menu, but this seems to be a problem for GMs only.

My guess is, that players can't drag'n'drop components from the sidebar, so TouchVTT assumes the user wants to right-click, whereas the Gamemaster has the option to drag'n'drop components onto the board and TouchVTT seems to prioritize drag'n'drop before the context menu.

Now, I don't find the drag'n'drop functionality to be too important during play. The context-menu, on the other hand, is. Without it, it is impossible to be the GM on a tablet, to be honest. You can't change scenes, for example, as you'd need the context-menu for that. You can't delete tokens from the current scene either.

**Comment by wickermoon** [comment]
Okay, so the long-press for GMs is even more complicated. As long as you long-press on the icon of actors or items, it'll open the context menu. But there's no icon for scenes. If you remote-debug the browser, though, you can use long-press on the debugging workstation with a simple mouse click-hold and that will also open the context menu. Trying the same on the tablet won't do anything but start a drag operation, though.

**Comment by wickermoon** [comment]
An a last one: It is possible to open the context-menu on the tablet, as long as you time your long-press very, very well. You must press long enough to not simply trigger a left-click, but not too long to trigger a drag'n'drop. This is super finnicky.

**Comment by Aioros** [comment]
This should be solved in the latest version, where long press should work as expected on mostly everything. Let me know if this issue is still present for you.

The drag'n'dropping part is still missing, but I'm going to track that on #52
