### ISSUE TITLE
Foundry V10 Compatibility

### ISSUE THREAD

**Issue by TheMathKing** [Oromis/touch-vtt#49]
Hi, 

I was wondering if there is any update coming to make this compatible with V10? Would it work without?

**Comment by sroakjp** [comment]
So I damned the compatibility warning and went full speed ahead activating this module. This one has not caused me any issues. Plenty of others have. So far so good. This one is working for me in v10.

**Comment by yjeroen** [comment]
![image](https://user-images.githubusercontent.com/1303988/200177291-3b615375-a90b-4fe3-991c-a5a687e6c940.png)

Still giving a warning.

**Comment by Niclasp1501** [comment]
No Update?

**Comment by Synchronos** [comment]
It looks like this may be a fairly simple fix based on the console messages. 

[touch-vtt] The module "touch-vtt" is using "author" which is deprecated in favor of "authors" 
[touch-vtt] The module "touch-vtt" is using the old flat core compatibility fields which are deprecated in favor of the new "compatibility" object

**Comment by Karczman** [comment]
Any answer about updating?

**Comment by Niclasp1501** [comment]
Any answer about updating?

**Comment by erikhuck** [comment]
Now on foundry version 11 and I get this error:
<img width="1021" alt="image" src="https://github.com/Oromis/touch-vtt/assets/42946548/2e7035b9-996c-42e2-a528-2040408e787f">

**Comment by Niclasp1501** [comment]
I also need Touch-vtt for version 11. It would be really great and kind if you could take the time for an update. Alternatively, I wonder how I could help to upgrade the module to version 11.

**Comment by Aioros** [comment]
Closing this since we have a new version supporting v11 and v12 and I don't think we are officially maintaining support for v10 at this time. I'm willing to look into it if anybody still needs it, in which case I recommend opening a new issue.
