### ISSUE TITLE
Wall Drawing support

### ISSUE THREAD

**Issue by tcflanag** [Oromis/touch-vtt#5]
I have an unreleased module that adds better support for wall drawing on touch screens.

https://gitlab.com/tiwato/pen-wall-tools/-/blob/master/src/pen-tools.js

Is this something you'd be interested in a PR to absorb into your module?

**Comment by Oromis** [comment]
Oh, very nice! Yes, absolutely - that seems like a good fit!

**Comment by tcflanag** [comment]
Hmm.. I started merging my code, and I ended up with a bit more of change than I expected.  When testing your code, I found out that it didn't work with a stylus. 

I've been able to get it to work by changing your bound events from touch to pointer, (and some rejiggering to get pinch zoom to work again).  Do you want this as two separate PRs, or one just one?

**Comment by Oromis** [comment]
Whatever works best for you. A single PR is fine too.

**Comment by Oromis** [comment]
PR is merged and regarding issues are solved. This feature will be in the next release.

**Comment by Oromis** [comment]
Released as v1.2.1
