### ISSUE TITLE
Request: Individual user setting to disable

### ISSUE THREAD

**Issue by weihanderz** [Oromis/touch-vtt#54]
TouchVTT seems to be required for some modules such as mobile improvements while conflicting for others such as material plane. It would be useful to be able to disable the module on a per user setting, depending on the use case of that user.

**Comment by cpedroson** [comment]
Was this ever solved for?  Im using an android tablet for my GM client and an old android smartphone for the player's shared client (i.e. TV with touchscreen bar).  Im using Material Plane which is conflicting with TouchVTT.   I would like to be able to turn of VTT on the player client.
