### ISSUE TITLE
can't pause/unpause in touch mode

### ISSUE THREAD

**Issue by instantrice** [Oromis/touch-vtt#55]
I've searched, read docs, googled, reddited, etc. I can find no way to toggle the pause state in this add-on. This is an issue for my GM who only has a mobile device.

**Comment by bcoudrin** [comment]
While waiting for a feature for that you can create yourself a code macro with simply :
`game.togglePause();`

Put it in the hotbar et you can easily pause/unpause using it.

**Comment by Aioros** [comment]
Solved in v1.12.1
