### ISSUE TITLE
Panning or Zooming on the Canvas is very jittery.

### ISSUE THREAD

**Issue by KelSolaar** [Oromis/touch-vtt#56]
Hello,

On any iGadget, e.g. iPad, iPhone, I tried panning and zooming is very jittery. I was wondering if it is expected.

Cheers,

Thomas

**Comment by LorduFreeman** [comment]
Probably not but the module hasn't even been updated for the current Foundry version - bugs are expected at this state.

**Comment by DiceAndEasy** [comment]
You can work around this issue by changing the Zoom/Pan Gestures option to Zoom with 2 fingers, pan with 3 fingers. Note that this setting is on a per user basis meaning that each user will have to change it themselves.

**Comment by Aioros** [comment]
I changed the way we handle zoom & pan together and it should be much smoother now. I'll wait to close this issue since it's a tricky one and I would like some feedback first.

**Comment by Aioros** [comment]
Closing this since it should be fixed since v1.12.1
