### ISSUE TITLE
v11 Update?

### ISSUE THREAD

**Issue by bertodactyl** [Oromis/touch-vtt#58]
Is there still work being done on this? Looks like TouchVTT was compatible with v10 (even with no update) but is borked on v11?

**Comment by Oromis** [comment]
I read somewhere that v11 disabled modules that weren't explicitly updated for v10. With the latest version, touch-vtt should be compatible with v10, so please try it on v11 :)

**Comment by r-valyar** [comment]
Looking forward to the update, as it can't be installed on v11
![image](https://github.com/Oromis/touch-vtt/assets/63558984/dd11dfd8-b3ea-48db-97a8-6dfd9de33483)

**Comment by r-valyar** [comment]
I fixed this in my local instance, but I would prefer this to be updated in the main module

**Comment by Oromis** [comment]
@Athemis @r-valyar does the module work on v11? I have no time to test myself unfortunately.

**Comment by xaqaria** [comment]
> @Athemis @r-valyar does the module work on v11 when you make this change? I have no time to test myself unfortunately.

@Oromis 

I just submitted pull request #60 that:

1. removes `"maximum" ` value per @Athemis's suggestion
2. changes line 2 per the pop-up warning in FVTT11:
    `  "name": "touch-vtt",`
    to
    `  "id": "touch-vtt",`
3. changed `"version": "1.11.01b"`

I performed a smoke test and had it running during a 2 1/2 hour session, though it wasn't put to much use.

@Athemis and @r-valyar have you found any issues using the rest of the module in your own setups?

**Comment by xaqaria** [comment]
After updating and testing I installed another module that requires libwrapper.  Once enabled, libwrapper will produce an error message that TouchVTT is out of date and presents a message below.

Disabling libWrapper (as well as Levels and Wall Height that each rely upon it) causes the error to go away.

libWrapper 1.12.12.1
Wall Height 5.0.1
Levels 4.1

```
LibWrapperPackageError: lib-wrapper. Error detected in module TouchVTT. It is likely this module has not been updated for FVTT Version 11 Stable.

This is *not* a libWrapper bug.

Find information about this module here: https://github.com/Oromis/touch-vtt
Report this issue here: https://github.com/Oromis/touch-vtt/issues

== Technical Details:
Detected by libWrapper.
Package ID= touch-vtt
Error= Can't wrap 'MouseInteractionManager.prototype._handleClickLeft', target does not exist or could not be found.

[Detected 2 packages: lib-wrapper, touch-vtt]
    at new 🎁constructor (libWrapper-wrapper.js:111:11)
    at libWrapper-api.js:82:18
    at de (libWrapper-api.js:155:9)
    at 🎁register [as register] (libWrapper-api.js:525:14)
    at X (touch-vtt.js:1:12745)
    at Object.fn (touch-vtt.js:1:19795)
    at #call (foundry.js:730:20)
    at Hooks.callAll (foundry.js:687:17)
    at Game.initialize (foundry.js:8573:11)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁libWrapperInit (libWrapper-api.js:805:11)
```

**Comment by Oromis** [comment]
@xaqaria thanks for testing it out! Lemme check this out in the code, possibly this handler was renamed.

**Comment by Oromis** [comment]
Ah, seems a method has been made private in v11. I disabled the feature easy targeting feature for now.

Just released version 1.11.0. It loads fine for me, but I currently don't have a touchscreen at hand so I can't test the functionality. I'd appreciate you testing it!

**Comment by Zamrod** [comment]
The current version listed inside Foundry is 1.10.0 and it won’t install since that version still says it only works in v10. I believe the version and link inside the foundry web site needs to be updated

**Comment by Oromis** [comment]
Sorry, forgot to publish the package. Try again please :)

**Comment by Rhioppe** [comment]
Thank you for updating. Currently I experience an issue with selecting and dragging token. It seems that selecting a token automatically counts as a double click and opens op the charakter sheet. Moving the map with both two and three fingers and using the interface works fine for me.

**Comment by lslavkov** [comment]
Is this being resolved? If so can we close this Issue so we know that TouchVTT for V11 has being updated?

**Comment by Oromis** [comment]
Unfortunately I don't currently have access to a touch laptop which I would need to debug this issue :/

I can't promise anything :(

**Comment by Terrox** [comment]
Why is it Minimum v11? it can't be installed or upgraded on v10 now.

**Comment by farling42** [comment]
The Foundry Developers have said that they were maybe too eager to make some protected functions private, so if you raise the issue about handleClickLeft then they might return it to being a protected function instead of private.

**Comment by this-gavagai** [comment]
I'll always be grateful to @Oromis for this module. It gave my table and many others a lot of joy.

With v11, I'm running into a few different issues, including the character sheet problem. More significantly, even, I'm not any longer able to move tokens. The token picks up and drags fine, but when I release the touch from the screen Foundry isn't picking up the drop event. I've been digging into the code here to see if I could get it working, but there's something weird going on between Foundry and PIXI with pointerout events that I'm not understanding.

In the meantime, I've been playing around with a very different approach than the one taken in this module. It's not nearly as polished, and I'm not nearly as elegant a coder as @Oromis, but it's getting the job done at my table. I hope it's okay to post it here, in case it's helpful to anyone.

```javascript
function setupTouchTweaks() {
  const ZOOM_SPEED = 2
  const PAN_SPEED = 4
  const screen = document.querySelector('canvas#board')

  const hammer = new Hammer(screen)
  const pinch = hammer.get('pinch').set({ enable: true })
  const pan = hammer.get('pan').set({ direction: Hammer.DIRECTION_ALL, pointers: 2, threshold: 0 })
  pinch.recognizeWith(pan)

  hammer.on('pinchstart', getBaseScale)
  hammer.on('pan', panHandler)
  hammer.on('pinch', pinchHandler)

  let base_scale
  function getBaseScale(ev) {
    base_scale = canvas.stage.scale.x
  }

  function pinchHandler(ev) {
    // foundry doesn't 
    canvas.controls.select.active = false
    canvas.pan({
      scale: base_scale * Math.pow(ev.scale, 1 / ZOOM_SPEED)
    })
  }
  function panHandler(ev) {
    canvas.controls.select.active = false 
    canvas.pan({
      x: canvas.stage.pivot.x - (ev.velocityX * PAN_SPEED) / canvas.stage.scale.x,
      y: canvas.stage.pivot.y - (ev.velocityY * PAN_SPEED) / canvas.stage.scale.x
    })
  }

  // Foundry doesn't feed touch-based pointerup events back to the token
  // so we have to do it manually
  canvas.tokens.addEventListener('pointerup', (e) => {
    canvas.tokens.children.forEach((c) => {
      c.children.forEach((t) => {
        if (t.interactionState) t.dispatchEvent(e)
      })
    })
  })
}

```

NB: This code uses [Hammer.js](http://hammerjs.github.io) as a dependency for touch gesture interpretation. You'll have to source it in your module (or load it dynamically if you're trying to run this code from a macro).

**Comment by dan-cave** [comment]
I've taken quite a bit of inspiration from touch-vtt for a module I've recently created. It provides touch screen support for Foundry V11, but not in the exact same way that touch-vtt does. 

https://foundryvtt.com/packages/gaming-table/
https://github.com/dan-cave/gaming-table


It doesn't support gestures to zoom/pan, but you can pan and zoom with double, triple, and quadruple clicking for pan, zoom in, and zoom out respectively. I was never able to get the gestures to work well with my setup, so that user experience works best for me.

Getting touch support into foundry V11 required me to make a custom `MouseInteractionManager` and register it everywhere the regular `MouseInteractionManager` would exist. I personally think it was a pretty aggressive way to go, and will probably break in subsequent builds beyond V11.303, but I couldn't find any other solutions.

@Oromis  I'm not sure if you support introducing a custom `MouseInteractionManager` like I did in gaming-table, but if you do I could work on porting my changes over to touch-vtt so people can continue using this module as well. It's definitely not a sanctioned use of the API, but drastic API changes call for drastic measures haha. If you'd like some more info about my reasoning lmk.

If anyone would like to try it out, please check out the readme. I was only able to test this with a small number of touch screen devices.

**Comment by Aioros** [comment]
Closing this since v1.12 has just been released. Feel free to open a new issue for any problem with the new version in v11.
