### ISSUE TITLE
Release v1.9.2?

### ISSUE THREAD

**Issue by CapivaraTupiniquim** [Oromis/touch-vtt#59]
Has the module been updated to v10? I can't install v1.9.2

**Comment by r-valyar** [comment]
There is issue when updating to version above 1.9.1, this is output from module update: 
![image](https://github.com/Oromis/touch-vtt/assets/63558984/ff289c11-af35-4c4c-834b-be35a55e6baa)

**Comment by Oromis** [comment]
The last release was incomplete. Let me check it...

**Comment by Oromis** [comment]
Released 1.10.0, please check it out :)

**Comment by r-valyar** [comment]
Yes, this updates on v10, though v11 is not
