### ISSUE TITLE
Touching token open player sheet

### ISSUE THREAD

**Issue by raremind1071** [Oromis/touch-vtt#62]

**Comment by patrickmohrmann** [comment]
I agree, it would be great to have an option not to do so that would make game play much easier

**Comment by hiszpek** [comment]
I found a way for this to work, but it requires modifying the game files manually https://github.com/Oromis/touch-vtt/issues/61#issuecomment-1723727061

**Comment by Aioros** [comment]
Closing as duplicate of #61
