### ISSUE TITLE
Touch input doesn’t work on canvas on iPad Pro 2022

### ISSUE THREAD

**Issue by Zamrod** [Oromis/touch-vtt#63]
I’ve tried using the module in both Foundry 10.291 with version 1.10.0 and in Foundry 11.305 with version 1.11.0 both were running dnd5e 2.2.2. Touch works everywhere except the canvas.

This is running on iOS 16.5.1 (so safari 16.5) using an iPad Pro 12.9 6th Gen.

**Comment by Aioros** [comment]
Hi, let me know if this issue is still relevant after updating to the new v1.12 module, or if it has been solved.

**Comment by Aioros** [comment]
Closing the issue as stale, feel free to open a new one if it's still relevant.
