### ISSUE TITLE
Update for v12, now that basic touch functionality has been restored in Foundry core?

### ISSUE THREAD

**Issue by Gnurrf** [Oromis/touch-vtt#66]
Are there any plans to update TouchVTT for Foundry v12, now that the basic touch functionality (e.g., reliable token selection and movement) have been restored in core after they were killed in v11?

Touch in v12 core does not cover the very useful features which were supported by TouchVTT. such as the pan/zoom gestures.

According to the Foundry devs, the changes to update TouchVTT for v12 should be relatively limited:

"Modules using our API should benefit from the patch. Those handling events separately should simply ensure they handle pointer events instead of mouse events if they intend to capture mouse and touch events."

(from https://github.com/foundryvtt/foundryvtt/issues/10236 )

**Comment by Aioros** [comment]
Thought I'd reply here instead of opening a new one: I submitted PR #67 , which (at least on my devices) restores all functionality for this module in Foundry v11 and v12. I'm not sure if this repository is still active, though. In case we get no answer or Oromis is not up for it anymore, I wouldn't mind taking over development of the module.

**Comment by Oromis** [comment]
Thank you @Aioros for doing this! I'd be happy to pass on ownership of the module as I neither have the time nor a device to test touch interactions on any more.

**Comment by Aioros** [comment]
Thanks @Gnurrf , any help with testing will be useful. I believe we are keeping this repository, we're coordinating to get the new release out soon.

**Comment by Aioros** [comment]
TouchVTT v1.12 has just been released. I'm going to close this issue, and I imagine we will get quite a few new ones soon.

**Comment by 50gnr** [comment]
@Aioros any chance of adding in the ability to not have players sheets open on token double click? and cant wait to update module tonight and see your hard work!!

**Comment by Aioros** [comment]
Yep, that should (hopefully) be also fixed in the new version (let me know if it's not!)

**Comment by Aioros** [comment]
Wait, nevermind, I misread that. I remember a similar old issue now. Can I ask what the purpose of that would be? I would think that double clicking rarely happens accidentally.

**Comment by 50gnr** [comment]
for some reason my touches keep double registering from IR frame and opens the sheets instead of moving tokens occasionally. Your updates might have solved that, i will double check in a few hours on my set up!
