### ISSUE TITLE
[Bug] Folders flickering on click

### ISSUE THREAD

**Issue by BokuNC** [Oromis/touch-vtt#71]
I found something weird and it just started, everything was fine some days ago.

Using a mobile touch device and trying to open folders on Foundry makes them open and close very quickly. The long press kinda works, but its dragging the folder and isn't opening a "right-click" interaction.

I'm using the last Touch VTT version (2.0.3) and Foundry VTT V12.328.

I'll roll back into the 1.12.1 version for now, just in case.

---

Update: Rolled back into 1.12.1 solved the problem. Could it be related to the pointer rework, maybe? I don't really know.

**Comment by Aioros** [comment]
Interesting, thanks. It seems fine on v11 at a quick glance so it's probably something v12-specific, but I'll look into it.
