### ISSUE TITLE
Drag and Drop Token not working on Windows

### ISSUE THREAD

**Issue by mustangsami** [Oromis/touch-vtt#72]
Hi there,

Was happy to see new versions of TouchVTT. I wanted to try this on my gaming table which is powered by an IR Sensor on top of a TV, using a Windows Laptop running chrome. The IR sensor should use the  standard Windows Multi Touch behavior. I am on V11.315 of foundry.

When I try to move a token by dragging, it creates a shadow of the token but releasing the touch, where I want to move the token doesn't have an effect.

I didn't see any errors in the console. 

It seemed similar to the way it behaved on versions of Touch VTT prior to 1.12. 

However, it works perfectly on an Android tablet, so perhaps this is Windows specific.

Pinch to zoom and panning are working perfectly in this version.

Thanks

**Comment by Aioros** [comment]
I'll see if I can replicate it somehow. Mind if I ask you the Chrome version too?

**Comment by mustangsami** [comment]
Sure, it's 126.0.6478.127, I also tried it on Edge but it had the same issue.

Thanks

**Comment by Aioros** [comment]
Hey, so diagnosing this one is going to be tricky. If you're willing, the latest version of the module (2.0.5) has a "debug mode" setting that will log some basic event info, you could enable it, try to click on the canvas, attempt to move a token, and then send me the resulting log (screenshot or any kind of copy/paste should be ok).

**Comment by olilan1** [comment]
Hi, I'm a friend of mustangsami, I've currently got his touchscreen set up in my possession. Here's the debug log you requested
[foundry-touchvtt-win-drag-not-working.log](https://github.com/user-attachments/files/16134839/foundry-touchvtt-win-drag-not-working.log)

Note: there's a bunch of "pointermove mouse" from when I moved the mouse during the test, but the bit where I was touching the screen is from the "pointerdown touch" bit I think.

I uncollapsed some of the events to give more info, if you need more I can get it.

Thanks!

**Comment by olilan1** [comment]
Btw I also tried TouchVTT on v12 with this setup, and dragging the tokens seems to work fine.

**Comment by Aioros** [comment]
Hey, that was quick, thanks! Yeah, that drag release issue is specific to v11. I don't see anything out of the ordinary in the log at a first glance, but I'll keep looking.

**Comment by Aioros** [comment]
Hey, I just released v2.0.6, which takes a different approach to the dragging issue. I'm cautiously optimistic that it should fix the issue for you guys. Let me know if that's the case or not.

**Comment by olilan1** [comment]
It works!

Huge thanks for getting to this so quickly. TouchVTT is really great on this big touchscreen :)

**Comment by Aioros** [comment]
Awesome! I'll close this issue, thanks again for your help.
