### ISSUE TITLE
Limit min and max zoom

### ISSUE THREAD

**Issue by blazingeclipse** [Oromis/touch-vtt#73]
The max zoom that I can achieve with with touchVTT is much greater than with mouse or touchpad. This holds for both zooming in and zooming out, and can result in the situation that the scene is so small its hard to see where it even is.

Possible suggested setting:
1) setting for limiting max zoom
2) A setting to limit zoom speed / sensitivity of zoom input so its much less likely to end up in that situation.

Apreciate the effort put into this module! Let me know if you need some clarification or testing done, happy to help!

**Comment by blazingeclipse** [comment]
![image](https://github.com/user-attachments/assets/5a24caa0-66b5-4bf4-8135-85aca641ff34)
for reference, this is a 8k by 4k background image. I can zoom out even further without issue.

Running 2.06 foundry VTT and V12.328 core.

**Comment by Aioros** [comment]
I'm inclined to add a couple of settings for max and min zoom, which are probably going to be useful in any case, but I am having trouble reproducing this. Do you mind trying disabling all other modules, then trying with and without TouchVTT to see if it still happens?

Also, is the Foundry app full-screen in that image? What is your screen resolution?

**Comment by blazingeclipse** [comment]
Ha! Got the culprit! In a turn of bitter irony, the module that caused the weird behavior was one I installed to limit the zoom....

Zoom/Pan options caused it! Ha! 

Still, I use a refurbished old large touchscreen that used to belong to a highschool of some sort as playing table, and its gotten a bit jittery in its twilight years caused by what I imagine must be continuous abuse by overworked teachers and understimulated students. A max zoom / max zoom speed, or perhaps a smoothness / sensitivity setting would do a lot to reduce the impact of a ghost-touch or the touchscreen losing track of a finger for a moment.

Unsure which of those would be the most useful to people, or how much effort it would take!

I'll try it later this week on the old beast, but on laptop with touchscreen it feels smoother than I remember from older versions of touchVTT. The jittery behavior on the large screen mostly happens when touches are located close to each other, due to the IR multi touch detection. 

Thanks for the response so far :) keep up the good work, its truly appreciated!

**Comment by Aioros** [comment]
Nice, thanks for the update! For the next release I'm including a zoom sensitivity setting, and a different algorithm to calculate the zoom value that should help with jitter and work better when the touches are closer together. I'll close this issue for now, let me know if you find any other issues.

**Comment by blazingeclipse** [comment]
Hot damn that was a fast fix. 'preciated! I'll give it a test right away!
