### ISSUE TITLE
Double Click to minimize not working with TouchVTT on

### ISSUE THREAD

**Issue by BokuNC** [Oromis/touch-vtt#74]
So, using both the last Foundry Update (v12.329) and Touch VTT 2.0.9, i noticed that i could no longer double click the windows to minimize them. Once i disable TouchVTT, everything works as intended. Not sure what may be happening here, but since this is a very much active module, I decided to bug report!

**Comment by Aioros** [comment]
I'll look into it, thanks. Latest version had some change to window management to address the opposite issue (tapping a window header was sometimes triggering a double click) and I might have overcorrected somehow.

**Comment by Aioros** [comment]
Ah, could you also let me know what browser you're using, in case it's relevant?

**Comment by BokuNC** [comment]
Oh, sure! Who detected the bug first was a player of mine, using Mozilla Firefox. Then i checked using Foundry Lightweight Client on Windows, so Edge Based, i believe.

**Comment by Aioros** [comment]
Welp, that bug was a little embarassing on my part. But it should be fixed now in v2.0.10, so let me know if you still have any issue after updating, and thanks again for the report!

**Comment by Aioros** [comment]
I'm actually reopening the issue because I suspect the fix might not be well supported on a few browsers. I'll make sure it's done better as soon as possible.

**Comment by Aioros** [comment]
Fixed (in a more widely supported way) in v2.0.11
