### ISSUE TITLE
Wrong manifest link in v2.1.0 module.json

### ISSUE THREAD

**Issue by farling42** [Oromis/touch-vtt#76]
The module.json of v2.1.0 in the release area (and inside the zip) has a specific manifest link rather than pointing at "downloads/latest".

**Comment by farling42** [comment]
Which is strange, because this repository has the github action to automatically update the module.json with the correct link information.

**Comment by Aioros** [comment]
Yep, my bad. I was remaking the workflows and I messed up the manifest URL for stable release. I'll fix it soon, thanks.

**Comment by Aioros** [comment]
Alright, sorry, I got a little lost there. v2.1.2 should work as it's supposed to. Let me know if you have issues updating.

**Comment by farling42** [comment]
Updating to 2.1.2 was fine, thanks!
