### ISSUE TITLE
Clicking links don't have the correct event information (so anchors don't work)

### ISSUE THREAD

**Issue by farling42** [Oromis/touch-vtt#79]
Foundry: 11.315
touch-vtt: 2.0.6
game system: shadowrun 5th edition, version 0.21.0

See https://github.com/farling42/fvtt-pdf-pager/issues/111

When handling clicking on links in document sheets, the `JournalEntryPage._onClickDocumentLink` handler (foundry.js:22651 in Foundry 11.315) has the wrong value for `event.currentTarget`.

With touch-vtt disabled, `event.currentTarget` points to the "a" element which was clicked.

With touch-vtt enabled, `event.currentTarget` points to the entire Journal window/app.

This prevents any handlers from decoding any anchor which might be present on the link (in my case, a page number within a PDF document).

This was tested on a desktop computer which does not have a touch screen.

----

A simple test is to create a journal text page with a subtitle that would require scrolling from the top of the page in order to view it. Then in another document create a link to that subtitle.  Clicking on that newly created link would normally scroll the page to make the subtitle visible, but with touch-vtt the top of the page is displayed instead.

**Comment by Aioros** [comment]
Uh, fascinating issue, thanks! I'll investigate and report back.

**Comment by Aioros** [comment]
I think I found the culprit, issue should be fixed now in v2.2.2. Let me know if that's not the case.

**Comment by farling42** [comment]
Yes, that has the problem fixed. Many thanks
