### ISSUE TITLE
token drag, Zoom & pan doesn't seem to work with IR Frame, on linux cilent

### ISSUE THREAD

**Issue by hometoast** [Oromis/touch-vtt#80]
TouchVTT v2.2.1
Foundry v12.330
Debian 12
Google Chrome	127.0.6533.99 (Official Build) (64-bit) 
Touch screen, both the on-screen of lenovo flex, and an IR frame on external display.
only other module: libWrapper 1.12.14

--- 

dragging token with single finger causes a strange zoom out effect.   Verified that it DOES work with chrome on ipad pro.
Checked touch function of IR Frame and laptop screen with: https://cps-check.com/multi-touch-test

Settings:
![image](https://github.com/user-attachments/assets/65836fcb-a3d1-4e71-b9f7-025f25c28d5e)

screencap:
https://github.com/user-attachments/assets/1866403b-f9db-4ed6-af5f-df7ad0f4f6db

Excerpt from console: 
[single-finger-token-drag.txt](https://github.com/user-attachments/files/16533887/single-finger-token-drag.txt)

**Comment by hometoast** [comment]
I'm the guy in discord that //originally// thought it didnt work at all. I just misunderstood the meaning of the [x] Core functionality setting. 

Enabled that, but I still have some issues. Long pressing, with the setting enabled, DOES bring up the extra hud elements and the UI does get enlarged.

I ran a clean/fresh install of foundry to test it this time.

**Comment by Aioros** [comment]
Hey, thanks for the report. That does look pretty weird, let me try to make sure that I understand what I'm seeing in the video: when you try to drag a token, the token stays there, and instead the scene zooms out?
If that's the case, a few questions while I investigate, if you have some time to help me out:

- does that happen every time?
- you mention that the issue is with both the IR frame and the actual laptop, is that right?
- can you create anything else on the scene (a drawing, a tile, a template) and drag it?
- does it happen if you just drag on an empty space like if you wanted to make a rectangle selection?
- when you drag and it zooms out, if you keep your finger pressed, can you also zoom in by moving the finger back?

**Comment by Aioros** [comment]
Oh, one more question (sorry, I know it's a lot of questions at this point): does it still happen if you choose "no zoom or pan gestures" in TouchVTT's settings?

**Comment by Aioros** [comment]
(I'll keep adding comments to this issue as a way to take notes, I guess)

I believe (judging by the video and the `pressure: 0` in the logs) what is happening here is that you are basically working with a touchpad, either an actual one, or one emulated by the IR frame. And, well, I'm embarassed to admit that I'm discovering today that some touchpads do not work well at all with (or without) TouchVTT.
I'll start seeing what can I do about that.

**Comment by hometoast** [comment]
- does that happen every time? 
  - Just about -- it jumps by a large amount so its hard to say exactly the same. but yes.
- you mention that the issue is with both the IR frame and the actual laptop, is that right?
  - correct.
- can you create anything else on the scene (a drawing, a tile, a template) and drag it?
  - I just tried a measurement template and a tile. Behaves the same.
- does it happen if you just drag on an empty space like if you wanted to make a rectangle selection?
  -  Yes. 
- when you drag and it zooms out, if you keep your finger pressed, can you also zoom in by moving the finger back?
  - I was initially going to say no. but I've found if I move my finger a TINY amount... 10s of pixels maybe? that I can get it to zoom in and out, like if I ONE-finger drag the token, slowly. the further I get away from the token, it will zoom out. reversing direction will bring it back. 
- does it still happen if you choose "no zoom or pan gestures" in TouchVTT's settings?
  - I gave that a try. Nothing happens at all on dragging with that setting off. But I couldn't drag the token either. If I disabled (core functions off), I can single-finger drag the token around.

And I'm happy to answer as many questions as you've got!  If you need or want me to test anything else, happy to do that as well. I regret that I didn't capture any screenshots or logs when trying the above things, end of a long workday.

**Comment by Aioros** [comment]
Hey, thanks for all the info, I really appreciate the help. I'm still trying to figure out what could be causing the issue, especially if it doesn't depend on the IR frame at all. I would expect the regular laptop's touch screen to work just like any other.
Just two last questions for now: 1) do you see any error in the console when that happens? and 2) does it make any difference if the IR frame is disconnected?

**Comment by hometoast** [comment]
I have a game scheduled for this Monday; I'll get you those answers then. (I unmount and remount the TV from the wall each time 🥺)

**Comment by Aioros** [comment]
Ah, sure, don't worry then. I thought you could just easily unplug the frame from the laptop.

**Comment by hometoast** [comment]
> Ah, sure, don't worry then. I thought you could just easily unplug the frame from the laptop.

Oh, I definitely can. I just meant that I had to put it away until Monday.

**Comment by Aioros** [comment]
I made a few changes based on some quirkiness I found in the Debian+Chrome combo. I'm not sure it's going to help your situation, but update to v2.2.3 when you have some time and let me know if anything changed.

**Comment by hometoast** [comment]
I gave it a try: Results:
dragging token movement now works. And the devlog is much less chatty in that regard.
2 finger zoom/pan still behaves similarly.

**Comment by Aioros** [comment]
Ok, glad that there was at least some progress. Can I ask you what you mean by "2 finger zoom/pan still behaves similarly"?

**Comment by hometoast** [comment]
> "2 finger zoom/pan still behaves similarly"
 
 So, when I try and pan/zoom with multiple fingers, it looks like Foundry is trying to draw multiple selection rectangles at the same time.  I should've captured that in a gif/video. I can do that next time I'm in there.

**Comment by Aioros** [comment]
I see. That's going to be tricky for me to diagnose without an actual Debian-based touch device I think. Just in case, though, in the meantime, update to the latest TouchVTT version (2.2.4) before trying again, there were some changes to touch gesture detection.

**Comment by hometoast** [comment]
It's been a minute. But I had some time to check this out again. I can report that on 2.2.9, one of my laptops work and one doesn't. The "better" lenovo still behaves as described, but an older dell is letting me zoom and pan with two fingers. (Both the built in digitizer on the lapto screen and with the IR Frame via USB.)

The older laptop acted the same when I opened this issue. So I'd say this is resolved.
Thank you for all your work on the module.
