### ISSUE TITLE
Journal index cannot be scrolled 

### ISSUE THREAD

**Issue by LEronsn** [Oromis/touch-vtt#82]
When trying to scroll the index of a journal page, the titles are moved instead of scrolled down or up

**Comment by Aioros** [comment]
Hey, I recently added a two-finger scrolling gesture for this kind of situation. Does that work for you in the journal?

**Comment by Aioros** [comment]
I tried it out, and yeah, even the two-finger scrolling gesture was failing. It should be fixed now in v2.2.3. Let me know if you are able to scroll using two fingers after updating.

**Comment by LEronsn** [comment]
Yes. With two finger scrolling it's working now. Thanks a lot
