### ISSUE TITLE
Panning/Zooming over a token sometimes also initiates a drag and drop

### ISSUE THREAD

**Issue by watermelonwolverine** [Oromis/touch-vtt#85]
Panning or zooming over a token sometimes also selects the token for drag and drop which causes visual issues and also moves the token to one of the fingers upon release.

**Comment by Aioros** [comment]
This should be fixed now in v2.2.4. Let me know if that's the case.

**Comment by watermelonwolverine** [comment]
I updated to 2.2.4. Issue seems to be fixed
