### ISSUE TITLE
Cannot activate enrichers in chat while canvas is disabled

### ISSUE THREAD

**Issue by kontokontovtt** [Oromis/touch-vtt#92]
I have found an issue while interacting with the chat and the canvas is disabled
When a pc is concentrating and gets damage the concentration button shows in the chat for the player to click
If the canvas is disabled the player cannot press the button 
The animation show it is interacted somehow but it stucks and nothing happens
With canvas enabled everything works ok

Probably there is some connection with the previous issue #91 (canvas disabled)
Probably there is some connection with the enrichers as the issue is applied only on them on chat
![image](https://github.com/user-attachments/assets/231f802f-faec-40ef-8e4c-67c51d79f1eb)

**Comment by Aioros** [comment]
Hey, I'm fairly sure this is not related to TouchVTT or any other module, really. I imagine the same would happen with no modules enabled, if you turned off the canvas from the core Foundry settings.

**Comment by kontokontovtt** [comment]
Yes indeed
Excuse me for that
