### ISSUE TITLE
This module breaks Foundry's wall tool

### ISSUE THREAD

**Issue by hirunatan** [Oromis/touch-vtt#93]
I've just found that this module breaks the wall tool in FoundryVTT. When all modules are deactivated, the tool works ok. And when I activate only this one, it breaks again.

I select the wall tool, drag & drop the mouse and a ghost wall follow the cursor. But when I release the button, it disappears and no wall is created. I open a scene that already have walls that I created some weeks ago, and the same occurs. The scene does have walls from the other moment, but now I can't add any new one, nor move the ones that exist. Although I can select a wall and delete it.

The most interesting thing is that I don't remember having changed any setting or updated modules nor the version of Foundry.

I've seen that this error occurs in browser console when I release the mouse drag:
![imagen](https://github.com/user-attachments/assets/4dd94cbd-a2a4-42ef-a4cb-1120f29a6555)

I'm using Mozilla Firefox version 130.0 (a recent one). I've tested this with Chromium and it works without problem. It seems to be related to a problem with Touch api support from Firefox.

**Comment by Aioros** [comment]
Hey, thanks for letting me know, the wall tool has always been a delicate part of the module. It looks like a reasonably easy fix but I'm away for a few days, I'll see if I can squeeze something out of a PC somewhere in the meantime.

**Comment by Aioros** [comment]
The newly released v2.2.10 should fix this issue. Let me know if that's the case for you after you update your module.

**Comment by hirunatan** [comment]
It works now. Your'e awesome! Thanks a lot!
