### ISSUE TITLE
TouchVTT cannot move token

### ISSUE THREAD

**Issue by UmeeZoomee** [Oromis/touch-vtt#95]
I am not able to drag my token around on my phone. I've tried Samsung: Internet Browser, and Google Chrome. Both of which did not seem to affect anything. All of the other features seem to be working fine, except the rotate buttons on the token also do not work. Thanks!

**Comment by Aioros** [comment]
Hey, thanks for the info. I saw you mentioning on the Foundry discord that the issue seemed to come from a different module (Monk's TokenBar). I can look into a possible compatibility problem but as far as I can see, Monk's TokenBar has some issues with dnd5e v4.0 at least. Is that your situation?

**Comment by UmeeZoomee** [comment]
I'm so sorry! Somebody mentioned in the Discord that I may have accidentally restricted a token's movement through Monk's Tokenbar. And they were right...

Thankyou so much for trying to help! Again, I'm very sorry.

And no... I am not yet on version 4. Still on v3.3.

**Comment by Aioros** [comment]
Got it, no problem. Glad everything is working fine then.
