### ISSUE TITLE
Template controls stop working after changing scene

### ISSUE THREAD

**Issue by olilan1** [Oromis/touch-vtt#96]
The template touch controls work great when placing a template from e.g. a spell card (PF2e) initially. When the template appears I can touch and drag it, and the x, rotate, and tick buttons appear.

However after changing scene, they stop working. Instead, when I touch the template and try to drag it, it disappears or doesn't move, or it starts placing a new template. The touch control buttons don't appear.

Refreshing makes it start working again.

Foundry v12 Build 331
PF2e 6.4.1

**Comment by Aioros** [comment]
This should be now fixed in v2.2.11. Thanks, and feel free to reopen it if you still have issues.
