### ISSUE TITLE
Long press on PF2e canvas effect/condition icons does not execute right click

### ISSUE THREAD

**Issue by surged20** [Oromis/touch-vtt#97]
In the PF2e system, conditions and effects for a token are displayed in a vertical column on the upper right of the canvas. On a desktop system, one may right click to remove (or reduce the counter) an effect/condition.

A long press with TouchVTT does not seem to do this but rather shows the hover text from the effect/condition.

**Comment by Aioros** [comment]
Hi, thanks for the info. This seems to work fine on my end. Could you let me know what device you're using? Operating system, browser, etcetera?

**Comment by Aioros** [comment]
Oh, also knowing Foundry version would be very important. I kind of assumed v12, but I'll check on v11 in the meantime.

**Comment by surged20** [comment]
Foundry 12.330, PF2e 6.5.1, all modules disabled except for TouchVTT. Normally I use the Mobile Sheet module alongside TouchVTT to make sidebar/sheets/canvas usable on the phone display, but it's disabled to verify this independently.
iOS 17.6.1 on an iPhone 14 with Chrome (I understand it's actually Safari Mobile/Webkit on the backend)

Long press on the Token HUD works fine for me though. Could this be a Safari mobile issue?

**Comment by surged20** [comment]
Couple screenshots of what I see on my device before/after long pressing the effect icon.
![9808AA2F-716A-45AC-8789-90FC25E67733_1_102_o](https://github.com/user-attachments/assets/81cef6ba-5318-4009-b8f7-e023c6121962)
![E0518492-13B2-4CD8-BE40-E94B36F4E0EF_1_102_o](https://github.com/user-attachments/assets/3f59ba99-7773-4907-88ff-8576454bb9dd)

**Comment by Aioros** [comment]
Huh, interesting. I'm thinking maybe the hover div might be accidentally capturing the right click, but I'm not sure yet. I'll keep you posted.

**Comment by Aioros** [comment]
Alright, so, this doesn't really have a perfect solution. I think, at its core, it's a CSS issue with the hover tooltip that ends up covering the original element on small screens, so the cleanest approach would probably be either on modules like Mobile Improvements / Mobile Sheet, or on the PF2E system itself.

But there is one thing that I could do that made sense for TouchVTT: I added an option in v2.2.12 called Remove Hover Effects. If you enable it, you won't have tooltips like that at all (they are usually problematic on touch anyway), and you should be able to interact with this normally. Let me know if that works for you after updating the module.
